// public/js/validate.js（ブラウザと共用する純関数）の単体テスト: node --test test/
import test from 'node:test';
import assert from 'node:assert/strict';

const v = await import('../public/js/validate.js');

test('normalizeReg: 大文字化・全角→半角・空白と長音記号の始末', () => {
  assert.equal(v.normalizeReg(' ja819a '), 'JA819A');
  assert.equal(v.normalizeReg('ＪＡ８１９Ａ'), 'JA819A');
  assert.equal(v.normalizeReg('b—18901'), 'B-18901');
  assert.equal(v.normalizeReg('ja 819 a'), 'JA819A');
  assert.equal(v.normalizeReg(null), '');
});

test('isValidReg: 0001_init.sql の liveries_reg_format と同じ判定', () => {
  for (const ok of ['JA819A', 'JA01XJ', 'N12345', 'B-18901', 'ja73ab', 'HL7201']) {
    assert.ok(v.isValidReg(ok), `${ok} は通るべき`);
  }
  for (const ng of ['', 'J', 'JA', 'JA-', 'JAL123456', 'JA819A-1', 'JA819A!', '日本819']) {
    assert.ok(!v.isValidReg(ng), `${ng} は弾くべき`);
  }
  // 空白は正規化で落ちるので通る（入力の揺れを吸収する意図）
  assert.ok(v.isValidReg('JA 819A'));
});

test('isValidHttpUrl: http(s) とドメインを要求する', () => {
  assert.ok(v.isValidHttpUrl('https://www.ana.co.jp/ja/jp/'));
  assert.ok(v.isValidHttpUrl('http://example.com'));
  assert.ok(!v.isValidHttpUrl('example.com'));
  assert.ok(!v.isValidHttpUrl('javascript:alert(1)'));
  assert.ok(!v.isValidHttpUrl('ftp://example.com'));
  assert.ok(!v.isValidHttpUrl('https://localhost'));
  assert.ok(!v.isValidHttpUrl(''));
});

test('isValidDate: 実在する日付だけ通す', () => {
  assert.ok(v.isValidDate('2026-09-13'));
  assert.ok(!v.isValidDate('2026-02-30'));
  assert.ok(!v.isValidDate('2026/09/13'));
  assert.ok(!v.isValidDate(''));
});

test('validateLiveryForm: 必須は reg / name / source_url', () => {
  const bad = v.validateLiveryForm({});
  assert.equal(bad.ok, false);
  assert.ok(bad.errors.reg && bad.errors.name && bad.errors.source_url);
  assert.equal(bad.row, null);

  const ok = v.validateLiveryForm({
    reg: ' ja819a ', name: ' ピカチュウジェット NH ', name_en: '',
    airline: 'ANA', aircraft_type: 'B787-8', since: '2021-11-01', until_date: '',
    source_url: 'https://www.ana.co.jp/pr', note: 'ポケモン特別塗装機', color: '#F4C20D',
  });
  assert.equal(ok.ok, true);
  assert.deepEqual(ok.row, {
    reg: 'JA819A',
    name: 'ピカチュウジェット NH',
    name_en: null,
    airline: 'ANA',
    aircraft_type: 'B787-8',
    since: '2021-11-01',
    until_date: null,
    source_url: 'https://www.ana.co.jp/pr',
    note: 'ポケモン特別塗装機',
    color: '#f4c20d',
    status: 'pending',          // RLS の liveries_insert が要求する固定値
  });
});

test('validateLiveryForm: 140 字超の note・不正な色・逆順の期間を弾く', () => {
  const long = v.validateLiveryForm({
    reg: 'JA819A', name: 'x', source_url: 'https://a.example.com', note: 'あ'.repeat(141),
  });
  assert.match(long.errors.note, /140/);

  const color = v.validateLiveryForm({ reg: 'JA819A', name: 'x', source_url: 'https://a.example.com', color: 'red' });
  assert.ok(color.errors.color);

  const range = v.validateLiveryForm({
    reg: 'JA819A', name: 'x', source_url: 'https://a.example.com', since: '2026-05-01', until_date: '2026-04-01',
  });
  assert.ok(range.errors.until_date);
});

test('validatePhotoForm: 写真必須・同意チェック・未来の撮影日', () => {
  const noFile = v.validatePhotoForm({}, { requirePhoto: true, hasFile: false });
  assert.ok(noFile.errors.file);

  const noAgree = v.validatePhotoForm({ agree: false }, { requirePhoto: true, hasFile: true });
  assert.ok(noAgree.errors.agree);

  const future = new Date(Date.now() + 3 * 86400000).toISOString().slice(0, 10);
  const bad = v.validatePhotoForm({ agree: true, taken_on: future }, { requirePhoto: true, hasFile: true });
  assert.ok(bad.errors.taken_on);

  const ok = v.validatePhotoForm(
    { agree: true, taken_on: '2026-08-01', airport_icao: 'rjtt', caption: ' 羽田にて ' },
    { requirePhoto: true, hasFile: true }
  );
  assert.equal(ok.ok, true);
  assert.deepEqual(ok.row, {
    taken_on: '2026-08-01',
    airport_icao: 'RJTT',
    caption: '羽田にて',
    status: 'pending',       // RLS の photos_insert が要求する固定値
    is_primary: false,
  });

  // 写真なしのモード（新規登録のみ）では同意チェックを求めない
  const none = v.validatePhotoForm({}, { requirePhoto: false, hasFile: false });
  assert.equal(none.ok, true);
});

test('isAutoGeneratedName: handle_new_user() が作る形を初回と見なす', () => {
  assert.equal(v.isAutoGeneratedName('', 'a@example.com'), true);
  assert.equal(v.isAutoGeneratedName('ユーザー1a2b3c', null), true);
  assert.equal(v.isAutoGeneratedName('nakamura', 'nakamura@example.com'), true);
  assert.equal(v.isAutoGeneratedName('中村', 'nakamura@example.com'), false);
  assert.equal(v.isAutoGeneratedName('Taro Yamada', 'taro@example.com'), false);
});

test('storagePaths: {uid}/{uuid}.jpg と {uuid}_thumb.jpg', () => {
  const p = v.storagePaths('11111111-2222-3333-4444-555555555555', 'aaaa-bbbb');
  assert.equal(p.path, '11111111-2222-3333-4444-555555555555/aaaa-bbbb.jpg');
  assert.equal(p.thumbPath, '11111111-2222-3333-4444-555555555555/aaaa-bbbb_thumb.jpg');
  assert.throws(() => v.storagePaths('', 'x'), /uid と uuid/);
});

test('validateDisplayName / validateSnsUrl', () => {
  assert.equal(v.validateDisplayName('  中村  ').value, '中村');
  assert.equal(v.validateDisplayName('').ok, false);
  assert.equal(v.validateDisplayName('あ'.repeat(41)).ok, false);
  assert.equal(v.validateDisplayName('<script>').ok, false);
  assert.deepEqual(v.validateSnsUrl(''), { ok: true, error: null, value: null });
  assert.equal(v.validateSnsUrl('https://x.com/me').value, 'https://x.com/me');
  assert.equal(v.validateSnsUrl('x.com/me').ok, false);
});
